backend:
  name: github
  repo: WatchmanXI33/kalos-tech
  branch: main
  auth_type: token

media_folder: src/assets/images
public_folder: /src/assets/images

collections:
  - name: blog
    label: Blog Posts
    folder: src/content/posts
    create: true
    extension: md
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Published Date, name: published, widget: datetime, format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: Description, name: description, widget: string }
      - { label: Category, name: category, widget: string }
      - { label: Tags, name: tags, widget: list, allow_add: true, field: {label: Tag, name: tag, widget: string} }
      - { label: Draft, name: draft, widget: boolean, default: false }
      - { label: Body, name: body, widget: markdown }